name: Get Heroku config variable
description: Given an env key, gets the value from Heroku
author: 'Connor Walsh (@wconnorwalsh)'
inputs:
  heroku_api_key:
    description: API key from secrets.HEROKU_API_KEY
    required: true
  app_name:
    description: Heroku app name
    required: true
  config_key:
    description: Heroku config variable
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
